<?php
/**
 * Implements hook_preprocess_html().
 */
function navigation_preprocess_html(array &$variables) {
  unset($variables['page_top']['toolbar']);

  $variables['page_top']['navigation'] = [
    '#theme' => 'navigation',
    '#attached' => [
      'library' => [
        'navigation/navigation',
      ],
    ]
  ];

}

/**
 * Implements hook_theme().
 */
function navigation_theme($existing, $type, $theme, $path) {
  $items['navigation'] = [
    'variables' => [],
  ];

  return $items;
}
