services:
  # What to call the service hosting the site. Because there is only
  # one service, it is automatically set as the default service, which
  # does a few things
  #   1. Clones the git repository into the service container
  #   2. Exposes port 80 to the Tugboat HTTP proxy
  #   3. Routes requests to the preview URL to this service
  apache:
    # Use the available version of Apache by not specifying a version
    image: tugboatqa/httpd

    # A set of commands to run while building this service
    commands:
      # Commands that set up the basic preview infrastructure
      init: |
        # Install node 18.x
        curl -fsSL https://deb.nodesource.com/setup_18.x | bash -
        apt-get install -y nodejs

        # Install dependencies and build the project.
        npm install
        npm run build

        # Link the document root to the expected path. This example links the
        # dist directory to the docroot.
        ln -snf "${TUGBOAT_ROOT}/dist" "${DOCROOT}"
      build: |
        npm install
        npm run build
        